name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Instalar dependências
        run: npm ci

      - name: Fix permissions
        run: chmod +x node_modules/.bin/*

      - name: Rodar lint
        run: npm run lint

      - name: Checar vulnerabilidades de segurança
        run: npm audit --audit-level=high

      - name: Rodar testes com cobertura (mínimo 80%)
        run: npx jest --coverage

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test   # só roda se os testes passarem
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t projeto-final .

  docker-deploy:
    runs-on: ubuntu-latest
    needs: docker-build   # só roda se o build passar
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
          $(aws sts get-caller-identity --query Account --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: docker build -t ${{ secrets.ECR_REPOSITORY }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
          $(aws sts get-caller-identity --query Account --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          $(aws sts get-caller-identity --query Account --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
