name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Instalar dependências
        run: npm ci

      - name: Fix permissions
        run: chmod +x node_modules/.bin/*

      - name: Rodar lint
        run: npm run lint

      - name: Rodar testes com cobertura
        run: npx jest --coverage
